# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WIN_Index.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class WIN_Index(QtWidgets.QMainWindow):

    openCustomer = QtCore.pyqtSignal()
    openProduct = QtCore.pyqtSignal()
    openInvoice = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(QtWidgets.QMainWindow, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Index")
        self.resize(379, 252)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.BTN_Customer = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Customer.setGeometry(QtCore.QRect(40, 30, 301, 28))
        self.BTN_Customer.setObjectName("BTN_Customer")
        self.BTN_Product = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Product.setGeometry(QtCore.QRect(40, 80, 301, 28))
        self.BTN_Product.setObjectName("BTN_Product")
        self.BTN_Invoice = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Invoice.setGeometry(QtCore.QRect(40, 130, 301, 28))
        self.BTN_Invoice.setObjectName("BTN_Invoice")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 379, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Index", "Inicio"))
        self.BTN_Customer.setText(_translate("Index", "Gestion de Clientes"))
        self.BTN_Product.setText(_translate("Index", "Gestion de Productos"))
        self.BTN_Invoice.setText(_translate("Index", "Gestion de Faturas"))

    def connectEvents(self):
        self.BTN_Customer.clicked.connect(self.openCustomer)
        self.BTN_Product.clicked.connect(self.openProduct)
